# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
import os
import youtube_dl
from decimal import Decimal



class Ui_Dialog(object):
    

            


    def my_hook(self, d):
        if d['status'] == 'finished':
            file_tuple = os.path.split(os.path.abspath(d['filename']))
            print("Done downloading {}".format(file_tuple[1]))
        if d['status'] == 'downloading':
            p = d['_percent_str']
            p = p.replace('%','')
           # self.progress.setValue(float(p))
            self.progressBar.setValue(Decimal(p))
            QApplication.processEvents() 
            
            
            
        
    def clicked(self):
        directory =ui.lineEdit_2.text()
        URL = ui.lineEdit.text()
        print(directory)
        
        #ydl_opts = {}
        ydl_opts = {
                'outtmpl': self.lineEdit_2.text()+"/%(extractor)s-%(id)s-%(title)s.mp3",
                'format': 'bestaudio/best',
                #'format': 'mp3',
                'extractaudio': True,
                'audioformat': 'mp3',
                'progress_hooks': [self.my_hook],
                'noplaylist': True
            }
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download([URL])
             
            
    
    
    def exit(self):
        quit()
                
        
        
       # os.system('youtube-dl -x  --audio-format mp3 ' + URL)
        
     
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 453)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 130, 491, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 100, 121, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(210, 340, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 171, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 60, 491, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 390, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 390, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.clicked.connect(lambda:self.clicked())
        self.pushButton_2.clicked.connect(lambda:self.exit())
        self.retranslateUi(Dialog)
        self.progressBar.setMaximum(100)
        QtCore.QMetaObject.connectSlotsByName(Dialog)        
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "YouTube URL"))
        self.label_2.setText(_translate("Dialog", "Save Path"))
        self.pushButton.setText(_translate("Dialog", "Download"))
        self.pushButton_2.setText(_translate("Dialog", "Exit"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    
    Dialog.show()
    sys.exit(app.exec_())
